service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:eu-north-1:533267095900:table/Products"
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:eu-north-1:533267095900:table/Stock"
  - Effect: "Allow"
    Action:
      - sns:Publish
    Resource: "arn:aws:sns:eu-north-1:533267095900:createProductTopic"
  environment:
    AWS_ACCOUNT_REGION: eu-north-1
    PRODUCT_TABLE_NAME: Products
    STOCK_TABLE_NAME: Stock
    FRONT_END_APP: https://shop-react-redux-cloudfront-luka.s3.eu-north-1.amazonaws.com

functions:
  getProductsList:
    handler: getProductList/index.getProductList
    events:
      - httpApi:
          method: GET
          path: /products
    url:
      cors: true
  getProductsById:
    handler: getProductsById/index.getProductsById
    events:
      - httpApi:
          method: GET
          path: /products/{productId}
    url:
      cors: true
  createProduct:
    handler: createProduct/index.createProduct
    events:
      - httpApi:
          method: POST
          path: /products
  catalogBatchProcess:
    handler: catalogBatchProcess/index.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn

resources:
  Resources:
    catalogItemsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "catalogItemsQueue"
    createProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic

    productEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        TopicArn:
          Ref: createProductTopic
        Endpoint: banovicluka10@gmail.com


plugins:
  - serverless-esbuild