---
openapi: 3.0.0
info:
  title: product-service
  description: Product Service
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/BANOVICLUKA10/ProductService/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /products:
    get:
      tags:
      - Products
      description: Returns all products
      operationId: getProductsList
      responses:
        "200":
          description: All products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
              example:
              - id: 7567ec4b-b10c-48c5-9345-fc73c48a80aa
                title: ProductOne
                description: Short Product Description1
                price: 24
              - id: 7567ec4b-b10c-48c5-9345-fc73c48a80a1
                title: ProductTitle
                description: Short Product Description7
                price: 15
              - id: 7567ec4b-b10c-48c5-9345-fc73c48a80a3
                title: Product
                description: Short Product Description2
                price: 23
              - id: 7567ec4b-b10c-48c5-9345-fc73348a80a1
                title: ProductTest
                description: Short Product Description4
                price: 15
              - id: 7567ec4b-b10c-48c5-9445-fc73c48a80a2
                title: Product2
                description: Short Product Descriptio1
                price: 23
              - id: 7567ec4b-b10c-45c5-9345-fc73c48a80a1
                title: ProductName
                description: Short Product Description7
                price: 15
  /products/{productId}:
    get:
      tags:
      - Products
      description: Returns product with the provided ID
      operationId: getProductsById
      parameters:
      - name: productId
        in: path
        description: The product ID
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: Return single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "404":
          description: Product not found.
          content:
            application/json:
              schema:
                type: string
                example: Product not found.
components:
  schemas:
    Product:
      type: object
      properties:
        description:
          type: string
        id:
          type: string
        price:
          type: integer
        title:
          type: string
    inline_response_200:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
    inline_response_200_1:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 7567ec4b-b10c-48c5-9345-fc73c48a80aa
        title:
          type: string
          example: ProductOne
        description:
          type: string
          example: Short Product Description1
        price:
          type: number
          example: 24
